### ISSUE TITLE
Breaking change to `github.com/arduino/go-paths-helper.Path.IsInsideDir`

### ISSUE THREAD

**Issue by per1234** [arduino/go-paths-helper#21]
One of the result parameters parameters was removed from the `github.com/arduino/go-paths-helper.Path.IsInsideDir` method in https://github.com/arduino/go-paths-helper/commit/657985f4e8bb0767df6dfab71d5069b4f7ce88b2

The breaking change to the package API is reasonable, but it was not communicated to the module's users.

I suggest the following remediation measures:

- Make a 2.0.0 release (as advised [**here**](https://semver.org/#what-do-i-do-if-i-accidentally-release-a-backwards-incompatible-change-as-a-minor-version))
- Document the breaking change in the 2.0.0 release notes

**Comment by cmaglie** [comment]
We may also re-add the error result (even if it will be always `nil`) to fix 1.x series.

**Comment by cmaglie** [comment]
It looks like there is a lot of work to do for a v2 version: https://go.dev/blog/v2-go-modules

The suggested approach in the blog post will leave the `v1` version on the git root and the `v2` under the `v2/...` subdirectory, making the `v1` version more prominent which is something I don't like.

IMHO, it's not worth the effort, and we should revert the breaking change by reading the missing return error.
